# Hextra Theme Parameters
# Refer to https://imfing.github.io/hextra/docs/ for documentation

title = "Parscode"
description = "Learn data analysis and programming"

[logo]
  url = "img/logo-light.svg"
  dark = "img/logo-dark.svg"

[theme]
  default = "dark"

[search]
  enable = true

[navbar]
  [[navbar.nav]]
    title = "Articles"
    url = "/articles/"
  [[navbar.nav]]
    title = "Contributors"
    url = "/contributors/"

[footer]
  enable = true

[article]
  showDate = false
  showDateUpdated = false
  showReadingTime = false
  showTOC = true
  showTaxonomies = true

[list]
  showSummary = false
  showBreadcrumbs = true
  groupByYear = true

[social]
  # Add social media links here if needed
